ALTER TABLE `players`
  ADD COLUMN IF NOT EXISTS `TotalMatches` int(11) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `TotalWins` int(11) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `TotalLosses` int(11) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `TotalKills` int(11) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `TotalDeaths` int(11) NOT NULL DEFAULT 0;
